### ISSUE TITLE
Can we provide aarch64 docker dev image?

### ISSUE THREAD

**Issue by Smith-Cruise** [StarRocks/docker#12]
I can't build aarch64 image by myself, too many errors occour.

**Comment by luohaha** [comment]
> I can't build aarch64 image by myself, too many errors occour.

Try this https://hub.docker.com/repository/docker/starrocks/dev-env-mac-m1

**Comment by Smith-Cruise** [comment]
I see we still need to compile thirdparty by myself, it's waste lots of time. Can you provide thirdparty compiled image? Just like `starrocks/dev-env`.
